{
 "title": "Container Summary",
 "tags": [
  "Services",
  "Containers"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{container_label_io_rancher_container_name!=\"\"} > (time() - 15))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "content": "# Container Stats\n\nThis is an example of a dashboard showing information derived from both the Google cAdvisor process that runs within the Rancher agent process, and the Prometheus Rancher Exporter. \nThis data is scraped by prometheus and displayed through grafana."
  },
  {
   "title": "Total Host Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "format": "gbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) / 1024 /1024 / 1024"
    }
   ]
  },
  {
   "title": "Total Container Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "format": "gbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes) / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Number of Services Not Active",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rancher_service_state{state!=\"active\"}==1)"
    }
   ]
  },
  {
   "title": "Total Stacks in Rancher",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count({__name__=\"rancher_stack_state\"} > 0)"
    }
   ]
  },
  {
   "title": "Total Services in Rancher",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count({__name__=\"rancher_service_state\"} > 0)"
    }
   ]
  },
  {
   "title": "Total Containers in Rancher",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(rancher_service_scale)" }
   ]
  },
  {
   "title": "Active Rancher Services",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rancher_service_state{state=\"active\"} == 1",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}