{
 "title": "Rancher Stats",
 "tags": [ "Rancher" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "# Rancher Statistics\n\nThis dashboard exports metrics from within the rancher server JVM its-self. Instructions on how to do this can be found [here](https://github.com/infinityworksltd/Guide_Rancher_Monitoring).\n"
  },
  {
   "title": "Rancher Load Average",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "cattle_jvm_os_SystemLoadAverage",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm.os.SystemLoadAverage",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-11-10%2016%3A24%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D",
     "query": "SELECT mean(\"value\") FROM \"jvm.os.SystemLoadAverage\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "movingAverage(servers.944b1a09387f.jvm.os.SystemLoadAverage, '30min')"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "cattle_jvm_runtime_Uptime",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm.runtime.Uptime",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-11-10%2016%3A24%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D",
     "query": "SELECT mean(\"value\") FROM \"jvm.runtime.Uptime\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.944b1a09387f.jvm.runtime.Uptime"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cattle_jvm_memory_HeapMemoryUsage_used"
    },
    {
     "expr": "cattle_jvm_memory_HeapMemoryUsage_committed"
    }
   ]
  },
  {
   "title": "GC - MarkSweep Runs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "cattle_jvm_gc_ConcurrentMarkSweep_Collection_total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm.gc.MarkSweepCompact.CollectionCount",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22%22%2C%22range_input%22%3A%2221600s%22%2C%22end_input%22%3A%222015-11-11%2010%3A44%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D",
     "query": "SELECT mean(\"value\") FROM \"jvm.gc.MarkSweepCompact.CollectionCount\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "derivative(servers.944b1a09387f.jvm.gc.PS_MarkSweep.CollectionCount)"
    }
   ]
  },
  {
   "title": "Failed Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "20s",
     "expr": "{__name__=~\".*metric.*failed.*total\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "metric.event.failed.event_failed_agent_request.Count",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22%22%2C%22range_input%22%3A%2221600s%22%2C%22end_input%22%3A%222015-11-10%2016%3A3%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D",
     "query": "SELECT mean(\"value\") FROM \"metric.event.failed.event_failed_agent_request.Count\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias(derivative(servers.*.metric.event.failed.event_failed_agent_request.Count), 'Agent Request')"
    }
   ]
  },
  {
   "title": "Ping Overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase({__name__=~\".*event_request_ping_total\"}[60m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Ping Requested",
     "measurement": "metric.event.failed.event_failed_ping.Count",
     "query": "SELECT median(\"value\") FROM \"metric.event.failed.event_failed_ping.Count\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "target": "alias(derivative(servers.*.metric.event.request.event_request_ping.Count), 'Request Ping')"
    }
   ]
  },
  {
   "title": "Ping Success Ratio",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(increase({__name__=~\".*event_request_ping_total\"}[60m]) - increase({__name__=~\".*failed_event_failed_ping_total\"}[60m])) / increase({__name__=~\".*event_request_ping_total\"}[60m]) *100"
    }
   ]
  },
  {
   "title": "Process Execution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "{__name__=~\".*metric_process.*total\"} > 0",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "thread_pool.process.RejectedExecutionCount",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22%22%2C%22range_input%22%3A%2221600s%22%2C%22end_input%22%3A%222015-11-10%2016%3A15%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D",
     "query": "SELECT mean(\"value\") FROM \"thread_pool.process.RejectedExecutionCount\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "derivative(servers.*.metric.process_server.process_execution_process_already_in_progress.Count)"
    }
   ]
  },
  {
   "title": "DB Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "cattle_database_MaxActive",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "database.MaxActive",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-11-10%2016%3A20%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D",
     "query": "SELECT mean(\"value\") FROM \"database.MaxActive\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByMetric(servers.*.database.NumActive)"
    },
    { "expr": "cattle_database_NumActive" },
    { "expr": "cattle_database_NumIdle" }
   ]
  },
  {
   "title": "Thread Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "{__name__=~\"cattle_thread_pool.*\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "thread_pool.core.ActiveCount",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-11-10%2016%3A21%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D",
     "query": "SELECT mean(\"value\") FROM \"thread_pool.core.ActiveCount\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByMetric(servers.*.thread_pool.process.ActiveCount)"
    },
    { "expr": "cattle_jvm_thread_Thread_total" }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "cattle_jvm_thread_Thread_total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm.thread.ThreadCount",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222015-11-10%2016%3A29%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D",
     "query": "SELECT mean(\"value\") FROM \"jvm.thread.ThreadCount\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.*.jvm.thread.ThreadCount"
    }
   ]
  },
  {
   "title": "Open FIle Descriptors",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "calculatedInterval": "20s",
     "expr": "cattle_jvm_os_OpenFileDescriptor_total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm.os.OpenFileDescriptorCount",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-11-11%2010%3A37%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D",
     "query": "SELECT mean(\"value\") FROM \"jvm.os.OpenFileDescriptorCount\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.*.jvm.os.OpenFileDescriptorCount"
    }
   ]
  },
  {
   "title": "Timeout Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "20s",
     "expr": "cattle_metric_process_server_process_execution_timeout_total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metric.process_server.process_execution_timeout.Count",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22%22%2C%22range_input%22%3A%2221600s%22%2C%22end_input%22%3A%222015-11-10%2016%3A9%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D",
     "query": "SELECT mean(\"value\") FROM \"metric.process_server.process_execution_timeout.Count\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias(derivative(servers.*.metric.process_server.process_execution_timeout.Count), 'Timeouts')"
    }
   ]
  }
 ]
}