{
 "title": "Stack Status - Prometheus",
 "tags": [
  "Prometheus",
  "Services"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "# Stack Status\n\nThis dashboard was put together to demonstrate service & stack level metrics pulled from the Rancher API. \nThis is achieved through the rancher-api-integration service, a simple little application that's lightweight and open-source.\nThe benefit here being you can customise such dashboards to report on the health of your applications and services running on-top of rancher without having to provide access to the Rancher UI itself.\n\nBelow you can see the metrics ..\n* `rancher_service_state` which denotes the state of the service, using labels to add dimensions to the data. \n* `rancher_service_health_status` this is either 1 or 0 and is reported by the Rancher API depending on the 'health' status of an application."
  },
  {
   "title": "Service State",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rancher_service_state > 0) by (state)",
     "legendFormat": "{{ state }}  -- {{ name }} -- {{ instance }}"
    }
   ]
  },
  {
   "title": "Prometheus Stack Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rancher_stack_health_status{name=\"prometheus\", health_state=\"healthy\"}"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "rancher_service_health_status{name=\"prometheus\", health_state=\"healthy\"}",
     "prometheusLink": "http://10.196.94.101:9090/graph#%5B%7B%22expr%22%3A%22rancher_services%7Bname%3D%5C%22%24environment_name_urs%2FAudit%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222016-1-20%2013%3A8%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "rancher_service_health_status{name=\"grafana\", health_state=\"healthy\"}",
     "prometheusLink": "http://10.196.94.101:9090/graph#%5B%7B%22expr%22%3A%22rancher_services%7Bname%3D%5C%22%24environment_name_urs%2FAudit%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222016-1-20%2013%3A8%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "rancher_service_health_status{name=\"node-exporter\", health_state=\"healthy\"}",
     "prometheusLink": "http://10.196.94.101:9090/graph#%5B%7B%22expr%22%3A%22rancher_services%7Bname%3D%5C%22%24environment_name_urs%2FAudit%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222016-1-20%2013%3A8%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "cadvisor",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "rancher_service_health_status{name=\"cadvisor\", health_state=\"healthy\"}",
     "prometheusLink": "http://10.196.94.101:9090/graph#%5B%7B%22expr%22%3A%22rancher_services%7Bname%3D%5C%22%24environment_name_urs%2FAudit%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222016-1-20%2013%3A8%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Prometheus Rancher Exporter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "rancher_service_health_status{name=\"prometheus-rancher-exporter\", health_state=\"healthy\"}",
     "prometheusLink": "http://10.196.94.101:9090/graph#%5B%7B%22expr%22%3A%22rancher_services%7Bname%3D%5C%22%24environment_name_urs%2FAudit%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222016-1-20%2013%3A8%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Influx DB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "rancher_service_health_status{name=\"influxdb\", health_state=\"healthy\"}",
     "prometheusLink": "http://10.196.94.101:9090/graph#%5B%7B%22expr%22%3A%22rancher_services%7Bname%3D%5C%22%24environment_name_urs%2FAudit%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222016-1-20%2013%3A8%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D"
    }
   ]
  }
 ]
}